#! /bin/sh

sxhkd &
picom -f &
setxkbmap latam
nitrogen --restore &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Brave desktop='^2'
bspc rule -a Thunar state=floating
bspc rule -a spotify desktop='^4' state=floating
bspc rule -a Screenkey manage=off


